/* REXX */
/*----------------------------------------------------------------*/
/* Copyright Contributors to the zOS-Workflow Project.            */
/* PDX-License-Identifier: Apache-2.0                             */
/*----------------------------------------------------------------*/

AGENT_TASK_GROUP="${instance-EKMF_AGENT_TASK_GROUP}"

"PERMIT  CSFCRC  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFDEC  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFDSG  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFDSV  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFEDH  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFENC  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFIQF  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKDMR CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKDMW CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKDSL CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKIM  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKRC2 CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKRD  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKRR2 CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKRW  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKRW2 CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKYT  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFKYT2 CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFMGN  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFMVR  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFOWH  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKG  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKI  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKRC CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKRD CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKRR CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKRW CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPKX  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFPRR2 CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFRNGL CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFSAD  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFSAE  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFSYI  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFSYI2 CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"
"PERMIT  CSFSYX  CLASS(CSFSERV) DELETE ID("||AGENT_TASK_GROUP||")"

"SETROPTS RACLIST(CSFSERV) REFRESH"

